apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: general-purpose
  annotations:
    kubernetes.io/description: "General purpose NodePool for generic workloads"
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
        - key: karpenter.k8s.aws/instance-category
          operator: In
          values: ["t"]
        - key: karpenter.k8s.aws/instance-generation
          operator: Gt
          values: ["2"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
  annotations:
    kubernetes.io/description: "General purpose EC2NodeClass for running Amazon Linux 2 nodes"
spec:
  amiFamily: "AL2"  # Amazon Linux 2
  role: "KarpenterNodeRole-visionway-eks-cluster"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "visionway-eks-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "visionway-eks-cluster"
  amiSelectorTerms:
    - tags:
        aws:ec2launchtemplate: "true"
        karpenter.sh/discovery: "visionway-eks-cluster"
